# Docker Compose 配置文件 - 股票回测数据库服务
#
# 这个配置文件定义了股票回测系统所需的MySQL数据库容器服务
#
# 服务特点：
# 1. MySQL 8.0 官方镜像，稳定可靠
# 2. 持久化数据存储，重启不丢失数据
# 3. 独立网络，提升安全性
# 4. 标准端口映射，方便本地连接
#
# 数据库配置：
# - 数据库名称：stock_data
# - 用户名：stockuser
# - 密码：stock123456
# - 端口：3306
#
# 使用方法：
# 启动服务：docker-compose -p stock-backtest up -d
# 停止服务：docker-compose -p stock-backtest down
# 查看状态：docker-compose -p stock-backtest ps
# 查看日志：docker-compose -p stock-backtest logs mysql
#
# 注意事项：
# - 首次启动需要等待数据库初始化完成
# - 数据持久化在mysql_data卷中
# - 使用mysql_native_password认证插件确保兼容性

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stock_backtest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stock123456
      MYSQL_DATABASE: stock_data
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stock123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - stock_network

volumes:
  mysql_data:
    driver: local

networks:
  stock_network:
    driver: bridge